jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on Cypress Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
          group: "GitHub Actions"
          tag: "pipeline"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true
        id: cypress

      # 🔹 Generar reporte consolidado
      - name: Merge test reports
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json

      - name: Generate HTML report
        run: npx marge cypress/reports/report.json --reportDir cypress/reports

      # 🔹 Enviar el correo con adjunto
      - name: Send email with HTML report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "📊 Reporte Cypress - ASECCSS"
          to: "jcascantelopez@hotmail.com"
          from: "ASECCSS QA Bot <${{ secrets.EMAIL_USER }}>"
          html_body: |
            <h2>Resultados de pruebas Cypress</h2>
            <p>Repo: ${{ github.repository }}</p>
            <p>Commit: ${{ github.sha }}</p>
            <p>👉 El reporte completo está adjunto.</p>
          attachments: cypress/reports/mochawesome.html
