name: Cypress Tests with Email Notification

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # permite ejecutarlo manualmente desde GitHub Actions

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on Cypress Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
          group: "GitHub Actions"
          tag: "pipeline"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true
        id: cypress

      - name: Send email with results
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "📊 Reporte Cypress - ASECCSS"
          to: "jcascantelopez@hotmail.com"
          from: "Informe de Ejecución de Pruebas <${{ secrets.EMAIL_USER }}>"
          body: |
            Hola equipo,

            Se ejecutaron las pruebas Cypress con GitHub Actions.

            📌 Repo: ${{ github.repository }}
            📌 Commit: ${{ github.sha }}
            📌 Estado: ${{ steps.cypress.outcome }}

            👉 Detalles completos en Cypress Cloud:
            https://cloud.cypress.io/
