name: Pruebas Automatizadas con Cypress y CI con Pipeline/Action de GIT
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # permite ejecutarlo manualmente desde GitHub Actions

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on Cypress Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
          group: "GitHub Actions"
          tag: "pipeline"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true
        id: cypress

      # 游댳 Enviar correo con el reporte inline
      - name: Send email with inline HTML report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Informe Autom치tico de Resultado de Pruebas"
          to: "jcascantelopez@hotmail.com"
          from: "Equipo ASECCSS <${{ secrets.EMAIL_USER }}>"
          html_body: |
  
          
            <h2 style="color:#2c3e50; text-align:center; margin:0;">Reporte de Ejecuci칩n de Pruebas</h2>
            <h4 style="color:#7f8c8d; text-align:center; margin-top:5px; font-weight:normal;">
              Generado autom치ticamente por el pipeline de CI/CD en GitHub Actions
            </h4>
          
            <hr style="margin:20px 0;"/>
          
            <h3 style="color:#2c3e50;">Informaci칩n del Pipeline</h3>
            <p style="font-size:14px; line-height:1.6;">
              <b>Repositorio:</b> ${{ github.repository }}<br/>
              <b>Rama:</b> ${{ github.ref_name }}<br/>
              <b>Commit:</b> ${{ env.SHORT_SHA }} - ${{ github.event.head_commit.message }}<br/>
              <b>Autor:</b> ${{ github.event.head_commit.author.name }}<br/>
              <b>Ejecutado por:</b> ${{ github.actor }}<br/>
              <b>Estado del Job:</b> ${{ job.status }}<br/>
              <b>Workflow:</b> ${{ github.workflow }} (#${{ github.run_number }})<br/>
              <b>Fecha de ejecuci칩n:</b> ${{ github.run_started_at }}
            </p>

              Consulta el detalle completo en 
              https://cloud.cypress.io/invitation/26abb980-c5db-44d4-8ad0-f856e2dcca98
       
          
            <p style="color:gray; font-size:12px; text-align:center; margin-top:30px;">
               Este correo fue generado autom치ticamente por el pipeline de CI/CD.<br/>
              춸 ASECCSS QA Team
            </p>

