name: Cypress Tests with Email Notification

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # permite ejecutarlo manualmente desde GitHub Actions

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on Cypress Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
          group: "GitHub Actions"
          tag: "pipeline"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true
        id: cypress

      # 🔹 Enviar correo con el reporte inline
      - name: Send email with inline HTML report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Informe Automático de Resultado de Pruebas"
          to: "jcascantelopez@hotmail.com, franciscoalas@hotmail.com,atorresl8910@gmail.com"
          from: "Prueba <${{ secrets.EMAIL_USER }}>"
          html_body: |
              <h2>Reporte Cypress ASECCSS<h2>
              <p>Pruebas ejecutadas en CI/CD<p>
              <b>Repo:</b> ${{ github.repository }}
              <br>
              <b>Commit:</b> ${{ github.sha }}
              <br>
              <b>Estado:</b> ${{ job.status }}
              <hr>
              <p style="color:gray">Este correo fue generado automaticamente
