name: Cypress Tests with Email Notification

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true
        id: cypress

      - name: Send email with results
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Reporte Cypress - ASECCSS"
          to: "jcascantelopez@hotmail.com"
          from: "Informe de Ejecución de Pruebas  <${{ secrets.EMAIL_USER }}>"
          body: |
            Hola equipo,
            
            Se ejecutaron las pruebas Cypress con GitHub Actions

            Si quiere ver más detealle consulta en Cypress Cloud: 
            https://cloud.cypress.io/invitation/26abb980-c5db-44d4-8ad0-f856e2dcca98


