name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1] # Si quieres correr en paralelo cambia a [1, 2, 3]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on Cypress Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: "GitHub Actions"
          key: ${{ secrets.CYPRESS_RECORD_KEY }}

